# Generated by Django 5.2 on 2025-05-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0002_students_user_attendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
