# Generated by Django 5.2 on 2025-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0008_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
