# Generated by Django 5.2 on 2025-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0010_remove_attendance_username_attendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='period',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
