# Generated by Django 5.2 on 2025-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0005_faculty_username_alter_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='f_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
