# Generated by Django 5.2 on 2025-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0006_subject_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
