# Generated by Django 5.2 on 2025-05-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0009_period_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='username',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendo.subject'),
        ),
    ]
