# Generated by Django 5.2 on 2025-05-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo', '0011_attendance_period_period_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=20)),
                ('period', models.CharField(max_length=10, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendo.students')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendo.subject')),
            ],
        ),
    ]
